# NOTE: When installing, please, update this file with the correct subdomain!

image:
  repository: 319794837620.dkr.ecr.us-west-2.amazonaws.com/bookstore-front-end

api:
  url: https://api.dev.bookstore.techenvision.net