version: "3"
services: 
    clients-api:
        build: ./clients-api
        ports: 
            - "5003:5003"
        environment: 
            AWS_DEFAULT_REGION: us-west-2
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
