image:
  repository: 319794837620.dkr.ecr.us-west-2.amazonaws.com/bookstore-renting-api
  tag: 1.3.cf6de59f
serviceAccount:
  roleARN: arn:aws:iam::319794837620:role/bookstore-eks-X7b6Bawd-development-sa-renting-api-role