apiVersion: v1
kind: Service
metadata:
  name: {{ include "booksotre-front-end.fullname" . }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "booksotre-front-end-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "booksotre-front-end-proxy.selectorLabels" . | nindent 4 }}
