apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookstore-front-end.name" . }}-proxy-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bookstore-front-end-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bookstore-front-end-proxy.selectorLabels" . | nindent 4 }}
