apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "booksotre-front-end.fullname" . }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "booksotre-front-end-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "booksotre-front-end-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "booksotre-front-end-proxy.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: {{ template "booksotre-front-end.fullname" . }}-proxy-config
        configMap:
          name: {{ template "booksotre-front-end.fullname" . }}-proxy-config
      containers:
        - name: {{ .Chart.Name }}-proxy
          image: "nginx"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: {{ template "booksotre-front-end.fullname" . }}-proxy-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}