apiVersion: v1
kind: Service
metadata:
  name: {{ include "booksotre-front-end.name" . }}-service
  labels:
    {{- include "booksotre-front-end.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "booksotre-front-end.selectorLabels" . | nindent 4 }}
